
title: MalingIT
email: your-email@example.com
description: Website malingIT
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://maling-it.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
comment: maling-it/maling-it.github.io
# Build settings
plugins:
  - jekyll-feed
  - jekyll-archives
  
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:   # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

defaults:
  -
    scope:
      path: '_posts'          # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      permalink: /:categories/:title/
  -
    scope:
      path: _drafts
    values:
      comments: false
  -
    scope:
      path: '_pages'
      type: pages             # see `site.collections`
    values:
      layout: page
      permalink: /:title
  -
    scope:
      path: '_tools'
      type: tools          # see `site.collections`
    values:
      layout: tool
      permalink: /tools/:title/
  -
    scope:
      path: '_auth'
      type: auth
    values:
      layout: author
      permalink: /info/:slug/

collections:
  tools:
    output: true
    sort_by: order
  pages:
    output: true
    sort_by: order
  auth:
    output: true
    sort_by: order

sass:
  dir: '_sass'
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]
    
exclude:
  - '*.gem'
  - '*.gemspec'
  - tools
  - docs
  - README.md
  - LICENSE
  - gulpfile.js
  - node_modules
  # - '*.json'
  - rcm
  - package.json
  - yarn.lock
  - log.txt

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /:name/

# Pagination Settings
pagination:
  enabled: true
  per_page: 1
  permalink: '/:num/'
  title: '⚡️Terbaru'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  indexpage: index
  extension: html