name: telegram Notify

on:
  push:
    branches: [ master ]  
  release:    
    types:
      - published  
  workflow_dispatch: 
  
jobs:
  build:    
    runs-on: ubuntu-latest    
    steps:        
    - uses: avkviring/telegram-github-action@v0.0.15
      env:
        telegram_to: "-761730816"
        telegram_token: "5048625452:AAFeDR5IKx-ZOLaYXWRcq6hCB8NXof8JsTo"
        event: ${{ toJson(github.event) }}
